name: 'Nexploit Scan'
description: 'Run a Nexploit scan right in GitHub Action'
branding:
  icon: clock
  color: blue
inputs:
  api_token:
    description: 'Api Token. You can generate it in Organization section'
    required: true
  scan:
    description: 'Scan ID to wait for'
    required: true
  hostname:
    description: 'Hostname. Default is nexploit.app'
    required: false
  wait_for:
    description: 'Wait for first issue: *any*, *medium*, *high*'
    required: true
  timeout:
    description: Time in seconds for the action to wait for issues
    required: false
    default: 600

outputs:
  url:
    description: 'Url of the resulting scan'
runs:
  using: 'node12'
  main: 'dist/index.js'
