name: CI / Automated testing

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build GitHub Action
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci && npm install -g @vercel/ncc
      - name: Build release
        run: npm run lint && npm run build && npm run pack
      - name: Copy files to release
        run: |
          mkdir release
          cp README.md release/
          cp action.yml release/
          cp -R dist/ release/dist/
      - name: Start NeuraLegion Scan 🏁
        id: scan
        uses: NeuraLegion/run-scan@release
        with:
          api_token: ${{ secrets.NEXPLOIT_TOKEN }}
          name: GitHub scan ${{ github.sha }}
          discovery_types: |
            [ "crawler" ]
          module: "dast"
          crawler_urls: |
            [ "https://brokencrystals.com" ]
          hosts_filter: |
            [ ]
      - name: Wait for any issues ⏳
        id: wait
        uses: ./release
        continue-on-error: true
        with:
          api_token: ${{ secrets.NEXPLOIT_TOKEN }}
          scan: ${{ steps.scan.outputs.id }}
          wait_for: any
          timeout: 340 # in general cases we'll have a timeout and it is good for this test

